# Generated by Django 2.2.7 on 2020-09-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one', models.ImageField(upload_to='', verbose_name='Upload image one')),
                ('image_two', models.ImageField(upload_to='', verbose_name='Upload image two')),
            ],
        ),
    ]
